let sun = document.querySelector("#sun"),
    moon = document.querySelector("#moon"),
    body = document.querySelector("body"),
    cart = document.querySelector("#cart"),
    closeShopping = document.querySelector(".closeShopping"),
    homeBg = document.querySelector(".home_bg"),
    leftArrow = document.querySelector(".leftArrow"),
    rightArrow = document.querySelector(".rightArrow"),
    imageIcons = document.querySelectorAll(".image-icon"),
    list = document.querySelector(".product-right-bottom"),
    li = document.querySelectorAll(".list"),
    circle = document.querySelectorAll(".fa-circle"),
    allList = document.querySelector(".all-list"),
    listCard = document.querySelector(".listCard");
let total = document.querySelector(".total");
let quanity = document.querySelector(".quantity");
let bookType = document.querySelectorAll(".book-type");
const navMenu = document.getElementById("nav_menu"),
    navToggle = document.getElementById("nav-toggle"),
    navClose = document.getElementById("nav-close");